### ISSUE TITLE
Php 7.1 A non-numeric value encountered

### ISSUE THREAD

**Issue by hootsy** [imanilchaudhari/yii2-currency-converter#2]
After upgrading to Php 7.1 get error

`"name": "PHP Warning",
    "message": "A non-numeric value encountered",
    "code": 2,
    "type": "yii\\base\\ErrorException",
    "file": "/code/vendor/imanilchaudhari/yii2-currency-converter/CurrencyConverter.php",
    "line": 46,
    "stack-trace": [
        "#0 ../imanilchaudhari/yii2-currency-converter/CurrencyConverter.php(46): yii\\base\\ErrorHandler->handleError(2, 'A non-numeric v...', '/code/vendor/im...', 46, Array)",
        "#1 .......CurrencyConverter->convert('USD', 'NPR')",`

**Comment by chaimleich** [comment]
The web service used by the Yahoo provider is no longer available.

I created a pull request that adds a provider class for Open Exchange Rates. They have a free tier, which for most sites should be enough if you're caching the results.

**Comment by imanilchaudhari** [comment]
@hootsy please have a look at this [pull request](https://github.com/imanilchaudhari/yii2-currency-converter/pull/3). This may help you.
