### ISSUE TITLE
 Undefined offset: 1

### ISSUE THREAD

**Issue by matlae-ugly** [imanilchaudhari/yii2-currency-converter#7]
When i am trying to run a simple test convert i get this ERROR: 
Undefined offset: 1

1. in /home/mat-ugly/webserver/sites/projecty/vendor/imanilchaudhari/yii2-currency-converter/Provider/YahooApi.php at line 37
282930313233343536373839

        $ch = curl_init();
        $timeout = 0;
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_USERAGENT, 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)');
        curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
        $rawdata = curl_exec($ch);
        curl_close($ch);
 
        return explode(',', $rawdata)[1];
    }
}

**Comment by imanilchaudhari** [comment]
@matlae-ugly As of recent changes on Yahoo Terms of Service, the service is being discontinued.
That is, Yahoo provider doesn't work any more. Please use other providers for now.
We'll be removing the deprecated provider soon from code and documentation. Any Contribution is welcome.

[https://www.yiiframework.com/extension/yii2-currency-converter#c20541](https://www.yiiframework.com/extension/yii2-currency-converter#c20541)
